### ISSUE TITLE
Use Bona Nova font by Andrzej Heidrich

### ISSUE THREAD

**Issue by macbre** [macbre/wbc.macbre.net#31]
http://bonanova.wtf/ + [Fira Sans](https://fonts.google.com/specimen/Fira+Sans)

```css
@font-face {
  font-family: "BonaNova-Bold";
  src: url("../fonts/BonaNova/BonaNova-Bold.eot");
  src: url("../fonts/BonaNova/BonaNova-Bold?#iefix") format("embedded-opentype"), url("../fonts/BonaNova/BonaNova-Bold.woff") format("woff"), url("../fonts/BonaNova/BonaNova-Bold.ttf") format("truetype");
  font-weight: normal;
  font-style: normal;
}
@font-face {
  font-family: "BonaNova-Italic";
  src: url("../fonts/BonaNova/BonaNova-Italic.eot");
  src: url("../fonts/BonaNova/BonaNova-Italic?#iefix") format("embedded-opentype"), url("../fonts/BonaNova/BonaNova-Italic.woff") format("woff"), url("../fonts/BonaNova/BonaNova-Italic.ttf") format("truetype");
  font-weight: normal;
  font-style: normal;
}
@font-face {
  font-family: "BonaNova-Regular";
  src: url("../fonts/BonaNova/BonaNova-Regular.eot");
  src: url("../fonts/BonaNova/BonaNova-Regular?#iefix") format("embedded-opentype"), url("../fonts/BonaNova/BonaNova-Regular.woff") format("woff"), url("../fonts/BonaNova/BonaNova-Regular.ttf") format("truetype");
  font-weight: normal;
  font-style: normal;
}
```
